version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "⬆️"
    assignees:
      - "etc-tiago"
    labels:
      - "dependencies"
    versioning-strategy: "increase"